// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) Hafnova AG
//
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.0
// source: threat.proto

package threatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_DOMAIN           Type = 1
	Type_IPv4             Type = 2
	Type_IPv6             Type = 3
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "DOMAIN",
		2: "IPv4",
		3: "IPv6",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"DOMAIN":           1,
		"IPv4":             2,
		"IPv6":             3,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_threat_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_threat_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{0}
}

type PayloadAuthMode int32

const (
	PayloadAuthMode_PAYLOAD_AUTH_MODE_UNSPECIFIED PayloadAuthMode = 0
	PayloadAuthMode_USER                          PayloadAuthMode = 1
	PayloadAuthMode_API                           PayloadAuthMode = 2
)

// Enum value maps for PayloadAuthMode.
var (
	PayloadAuthMode_name = map[int32]string{
		0: "PAYLOAD_AUTH_MODE_UNSPECIFIED",
		1: "USER",
		2: "API",
	}
	PayloadAuthMode_value = map[string]int32{
		"PAYLOAD_AUTH_MODE_UNSPECIFIED": 0,
		"USER":                          1,
		"API":                           2,
	}
)

func (x PayloadAuthMode) Enum() *PayloadAuthMode {
	p := new(PayloadAuthMode)
	*p = x
	return p
}

func (x PayloadAuthMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadAuthMode) Descriptor() protoreflect.EnumDescriptor {
	return file_threat_proto_enumTypes[1].Descriptor()
}

func (PayloadAuthMode) Type() protoreflect.EnumType {
	return &file_threat_proto_enumTypes[1]
}

func (x PayloadAuthMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadAuthMode.Descriptor instead.
func (PayloadAuthMode) EnumDescriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{1}
}

type RequestField int32

const (
	RequestField_RF_DOMAIN     RequestField = 0
	RequestField_RF_IP         RequestField = 1
	RequestField_RF_TAG        RequestField = 2
	RequestField_RF_COMMENT    RequestField = 3
	RequestField_RF_CTAG       RequestField = 4
	RequestField_RF_META_KEY   RequestField = 5
	RequestField_RF_META_VALUE RequestField = 6
)

// Enum value maps for RequestField.
var (
	RequestField_name = map[int32]string{
		0: "RF_DOMAIN",
		1: "RF_IP",
		2: "RF_TAG",
		3: "RF_COMMENT",
		4: "RF_CTAG",
		5: "RF_META_KEY",
		6: "RF_META_VALUE",
	}
	RequestField_value = map[string]int32{
		"RF_DOMAIN":     0,
		"RF_IP":         1,
		"RF_TAG":        2,
		"RF_COMMENT":    3,
		"RF_CTAG":       4,
		"RF_META_KEY":   5,
		"RF_META_VALUE": 6,
	}
)

func (x RequestField) Enum() *RequestField {
	p := new(RequestField)
	*p = x
	return p
}

func (x RequestField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestField) Descriptor() protoreflect.EnumDescriptor {
	return file_threat_proto_enumTypes[2].Descriptor()
}

func (RequestField) Type() protoreflect.EnumType {
	return &file_threat_proto_enumTypes[2]
}

func (x RequestField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestField.Descriptor instead.
func (RequestField) EnumDescriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{2}
}

type PrivateKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          string                 `protobuf:"bytes,1,opt,name=algo,proto3" json:"algo,omitempty"`
	Priv          []byte                 `protobuf:"bytes,2,opt,name=priv,proto3" json:"priv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrivateKey) Reset() {
	*x = PrivateKey{}
	mi := &file_threat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateKey) ProtoMessage() {}

func (x *PrivateKey) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateKey.ProtoReflect.Descriptor instead.
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{0}
}

func (x *PrivateKey) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *PrivateKey) GetPriv() []byte {
	if x != nil {
		return x.Priv
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          string                 `protobuf:"bytes,1,opt,name=algo,proto3" json:"algo,omitempty"`
	Pub           []byte                 `protobuf:"bytes,2,opt,name=pub,proto3" json:"pub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_threat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKey) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

func (x *PublicKey) GetPub() []byte {
	if x != nil {
		return x.Pub
	}
	return nil
}

type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Wildcard      bool                   `protobuf:"varint,2,opt,name=wildcard,proto3" json:"wildcard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_threat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{2}
}

func (x *Domain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Domain) GetWildcard() bool {
	if x != nil {
		return x.Wildcard
	}
	return false
}

type InternetProtocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mask          int32                  `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternetProtocol) Reset() {
	*x = InternetProtocol{}
	mi := &file_threat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternetProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternetProtocol) ProtoMessage() {}

func (x *InternetProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternetProtocol.ProtoReflect.Descriptor instead.
func (*InternetProtocol) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{3}
}

func (x *InternetProtocol) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *InternetProtocol) GetMask() int32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

type Storage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Information:
	//
	//	*Storage_Domain
	//	*Storage_Ip
	Information   isStorage_Information `protobuf_oneof:"information"`
	First         int64                 `protobuf:"varint,5,opt,name=first,proto3" json:"first,omitempty"`
	Last          int64                 `protobuf:"varint,6,opt,name=last,proto3" json:"last,omitempty"`
	Tags          []string              `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Comments      []string              `protobuf:"bytes,8,rep,name=comments,proto3" json:"comments,omitempty"`
	Ctags         []string              `protobuf:"bytes,9,rep,name=ctags,proto3" json:"ctags,omitempty"`
	Metadatas     []string              `protobuf:"bytes,10,rep,name=metadatas,proto3" json:"metadatas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_threat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{4}
}

func (x *Storage) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Storage) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *Storage) GetInformation() isStorage_Information {
	if x != nil {
		return x.Information
	}
	return nil
}

func (x *Storage) GetDomain() *Domain {
	if x != nil {
		if x, ok := x.Information.(*Storage_Domain); ok {
			return x.Domain
		}
	}
	return nil
}

func (x *Storage) GetIp() *InternetProtocol {
	if x != nil {
		if x, ok := x.Information.(*Storage_Ip); ok {
			return x.Ip
		}
	}
	return nil
}

func (x *Storage) GetFirst() int64 {
	if x != nil {
		return x.First
	}
	return 0
}

func (x *Storage) GetLast() int64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *Storage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Storage) GetComments() []string {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *Storage) GetCtags() []string {
	if x != nil {
		return x.Ctags
	}
	return nil
}

func (x *Storage) GetMetadatas() []string {
	if x != nil {
		return x.Metadatas
	}
	return nil
}

type isStorage_Information interface {
	isStorage_Information()
}

type Storage_Domain struct {
	Domain *Domain `protobuf:"bytes,3,opt,name=domain,proto3,oneof"`
}

type Storage_Ip struct {
	Ip *InternetProtocol `protobuf:"bytes,4,opt,name=ip,proto3,oneof"`
}

func (*Storage_Domain) isStorage_Information() {}

func (*Storage_Ip) isStorage_Information() {}

// Commit draft (LevelDB) — each row value is an `Input` (commands). JSON uses camelCase field names.
type CommitInputRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Input         *Input                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitInputRow) Reset() {
	*x = CommitInputRow{}
	mi := &file_threat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInputRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInputRow) ProtoMessage() {}

func (x *CommitInputRow) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInputRow.ProtoReflect.Descriptor instead.
func (*CommitInputRow) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{5}
}

func (x *CommitInputRow) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *CommitInputRow) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type CommitItemsQuery struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Idx    *uint32                `protobuf:"varint,1,opt,name=idx,proto3,oneof" json:"idx,omitempty"`
	Id     *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Limit  uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// "last" = last page (newest keys by lex order); JSON may use `anchor` or `fromEnd`.
	Anchor        *string `protobuf:"bytes,5,opt,name=anchor,proto3,oneof" json:"anchor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitItemsQuery) Reset() {
	*x = CommitItemsQuery{}
	mi := &file_threat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitItemsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitItemsQuery) ProtoMessage() {}

func (x *CommitItemsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitItemsQuery.ProtoReflect.Descriptor instead.
func (*CommitItemsQuery) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{6}
}

func (x *CommitItemsQuery) GetIdx() uint32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *CommitItemsQuery) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CommitItemsQuery) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CommitItemsQuery) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *CommitItemsQuery) GetAnchor() string {
	if x != nil && x.Anchor != nil {
		return *x.Anchor
	}
	return ""
}

type CommitItemsResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Ok         bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Idx        uint32                 `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	NextCursor string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Items      []*CommitInputRow      `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	// Pass as `cursor` to `commit-items` to load the previous page (forward pagination).
	PrevCursor    *string `protobuf:"bytes,5,opt,name=prev_cursor,json=prevCursor,proto3,oneof" json:"prev_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitItemsResult) Reset() {
	*x = CommitItemsResult{}
	mi := &file_threat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitItemsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitItemsResult) ProtoMessage() {}

func (x *CommitItemsResult) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitItemsResult.ProtoReflect.Descriptor instead.
func (*CommitItemsResult) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{7}
}

func (x *CommitItemsResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommitItemsResult) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *CommitItemsResult) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *CommitItemsResult) GetItems() []*CommitInputRow {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CommitItemsResult) GetPrevCursor() string {
	if x != nil && x.PrevCursor != nil {
		return *x.PrevCursor
	}
	return ""
}

type CommitStoragePutEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexUtf8     string                 `protobuf:"bytes,1,opt,name=index_utf8,json=indexUtf8,proto3" json:"index_utf8,omitempty"`
	Input         *Input                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStoragePutEntry) Reset() {
	*x = CommitStoragePutEntry{}
	mi := &file_threat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStoragePutEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStoragePutEntry) ProtoMessage() {}

func (x *CommitStoragePutEntry) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStoragePutEntry.ProtoReflect.Descriptor instead.
func (*CommitStoragePutEntry) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{8}
}

func (x *CommitStoragePutEntry) GetIndexUtf8() string {
	if x != nil {
		return x.IndexUtf8
	}
	return ""
}

func (x *CommitStoragePutEntry) GetInput() *Input {
	if x != nil {
		return x.Input
	}
	return nil
}

type CommitStoragePutRequest struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Idx     *uint32                  `protobuf:"varint,1,opt,name=idx,proto3,oneof" json:"idx,omitempty"`
	Id      *string                  `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Entries []*CommitStoragePutEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	// When true, existing row: union tags/ctags, merge metadatas by key, merge comments by id; JSON supports `importMerge` too.
	ImportMerge   *bool `protobuf:"varint,4,opt,name=import_merge,json=importMerge,proto3,oneof" json:"import_merge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStoragePutRequest) Reset() {
	*x = CommitStoragePutRequest{}
	mi := &file_threat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStoragePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStoragePutRequest) ProtoMessage() {}

func (x *CommitStoragePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStoragePutRequest.ProtoReflect.Descriptor instead.
func (*CommitStoragePutRequest) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{9}
}

func (x *CommitStoragePutRequest) GetIdx() uint32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *CommitStoragePutRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CommitStoragePutRequest) GetEntries() []*CommitStoragePutEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *CommitStoragePutRequest) GetImportMerge() bool {
	if x != nil && x.ImportMerge != nil {
		return *x.ImportMerge
	}
	return false
}

type CommitStoragePutResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Idx           uint32                 `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	Indices       []string               `protobuf:"bytes,3,rep,name=indices,proto3" json:"indices,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStoragePutResult) Reset() {
	*x = CommitStoragePutResult{}
	mi := &file_threat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStoragePutResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStoragePutResult) ProtoMessage() {}

func (x *CommitStoragePutResult) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStoragePutResult.ProtoReflect.Descriptor instead.
func (*CommitStoragePutResult) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{10}
}

func (x *CommitStoragePutResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommitStoragePutResult) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *CommitStoragePutResult) GetIndices() []string {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *CommitStoragePutResult) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CommitStorageSizeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Idx           uint32                 `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	CommitBytes   uint64                 `protobuf:"varint,3,opt,name=commit_bytes,json=commitBytes,proto3" json:"commit_bytes,omitempty"`
	RequestBytes  uint64                 `protobuf:"varint,4,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitStorageSizeResult) Reset() {
	*x = CommitStorageSizeResult{}
	mi := &file_threat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitStorageSizeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitStorageSizeResult) ProtoMessage() {}

func (x *CommitStorageSizeResult) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitStorageSizeResult.ProtoReflect.Descriptor instead.
func (*CommitStorageSizeResult) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{11}
}

func (x *CommitStorageSizeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommitStorageSizeResult) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *CommitStorageSizeResult) GetCommitBytes() uint64 {
	if x != nil {
		return x.CommitBytes
	}
	return 0
}

func (x *CommitStorageSizeResult) GetRequestBytes() uint64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

type BlockchainStorageSizeResult struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Ok           bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id           string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	ChainBytes   uint64                 `protobuf:"varint,3,opt,name=chain_bytes,json=chainBytes,proto3" json:"chain_bytes,omitempty"`
	RequestBytes uint64                 `protobuf:"varint,4,opt,name=request_bytes,json=requestBytes,proto3" json:"request_bytes,omitempty"`
	// `kernel.dataDir/request/chain:<id>/` — inverted index mirror for blockchain-search (not chain-local request DB).
	KernelRequestIndexBytes uint64 `protobuf:"varint,5,opt,name=kernel_request_index_bytes,json=kernelRequestIndexBytes,proto3" json:"kernel_request_index_bytes,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *BlockchainStorageSizeResult) Reset() {
	*x = BlockchainStorageSizeResult{}
	mi := &file_threat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainStorageSizeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainStorageSizeResult) ProtoMessage() {}

func (x *BlockchainStorageSizeResult) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainStorageSizeResult.ProtoReflect.Descriptor instead.
func (*BlockchainStorageSizeResult) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{12}
}

func (x *BlockchainStorageSizeResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BlockchainStorageSizeResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockchainStorageSizeResult) GetChainBytes() uint64 {
	if x != nil {
		return x.ChainBytes
	}
	return 0
}

func (x *BlockchainStorageSizeResult) GetRequestBytes() uint64 {
	if x != nil {
		return x.RequestBytes
	}
	return 0
}

func (x *BlockchainStorageSizeResult) GetKernelRequestIndexBytes() uint64 {
	if x != nil {
		return x.KernelRequestIndexBytes
	}
	return 0
}

type BlockchainExplorerControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainExplorerControlRequest) Reset() {
	*x = BlockchainExplorerControlRequest{}
	mi := &file_threat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainExplorerControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainExplorerControlRequest) ProtoMessage() {}

func (x *BlockchainExplorerControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainExplorerControlRequest.ProtoReflect.Descriptor instead.
func (*BlockchainExplorerControlRequest) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{13}
}

func (x *BlockchainExplorerControlRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlockchainExplorerControlResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Started       bool                   `protobuf:"varint,3,opt,name=started,proto3" json:"started,omitempty"`
	Stopped       bool                   `protobuf:"varint,4,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainExplorerControlResult) Reset() {
	*x = BlockchainExplorerControlResult{}
	mi := &file_threat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainExplorerControlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainExplorerControlResult) ProtoMessage() {}

func (x *BlockchainExplorerControlResult) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainExplorerControlResult.ProtoReflect.Descriptor instead.
func (*BlockchainExplorerControlResult) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{14}
}

func (x *BlockchainExplorerControlResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BlockchainExplorerControlResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockchainExplorerControlResult) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *BlockchainExplorerControlResult) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

type BlockchainExplorerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlockSum      string                 `protobuf:"bytes,2,opt,name=block_sum,json=blockSum,proto3" json:"block_sum,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainExplorerListRequest) Reset() {
	*x = BlockchainExplorerListRequest{}
	mi := &file_threat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainExplorerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainExplorerListRequest) ProtoMessage() {}

func (x *BlockchainExplorerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainExplorerListRequest.ProtoReflect.Descriptor instead.
func (*BlockchainExplorerListRequest) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{15}
}

func (x *BlockchainExplorerListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockchainExplorerListRequest) GetBlockSum() string {
	if x != nil {
		return x.BlockSum
	}
	return ""
}

func (x *BlockchainExplorerListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BlockchainExplorerListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type BlockchainExplorerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	BlockSum      string                 `protobuf:"bytes,2,opt,name=block_sum,json=blockSum,proto3" json:"block_sum,omitempty"`
	Ordinal       uint32                 `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Output        *Output                `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainExplorerEntry) Reset() {
	*x = BlockchainExplorerEntry{}
	mi := &file_threat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainExplorerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainExplorerEntry) ProtoMessage() {}

func (x *BlockchainExplorerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainExplorerEntry.ProtoReflect.Descriptor instead.
func (*BlockchainExplorerEntry) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{16}
}

func (x *BlockchainExplorerEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BlockchainExplorerEntry) GetBlockSum() string {
	if x != nil {
		return x.BlockSum
	}
	return ""
}

func (x *BlockchainExplorerEntry) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *BlockchainExplorerEntry) GetOutput() *Output {
	if x != nil {
		return x.Output
	}
	return nil
}

type BlockchainExplorerListResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Ok            bool                       `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            string                     `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Entries       []*BlockchainExplorerEntry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                     `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockchainExplorerListResult) Reset() {
	*x = BlockchainExplorerListResult{}
	mi := &file_threat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainExplorerListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainExplorerListResult) ProtoMessage() {}

func (x *BlockchainExplorerListResult) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainExplorerListResult.ProtoReflect.Descriptor instead.
func (*BlockchainExplorerListResult) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{17}
}

func (x *BlockchainExplorerListResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BlockchainExplorerListResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockchainExplorerListResult) GetEntries() []*BlockchainExplorerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *BlockchainExplorerListResult) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_threat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{18}
}

func (x *Metadata) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadata) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Server assigns `id` (8 random bytes) on enqueue for each Input.comment_add entry; wire/JSON use hex for display.
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_threat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{19}
}

func (x *Comment) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Index:
	//
	//	*Input_Domain
	//	*Input_Ip
	Index isInput_Index `protobuf_oneof:"index"`
	// New comments: set `text` only (`id` ignored until Output).
	CommentAdd []*Comment `protobuf:"bytes,10,rep,name=comment_add,json=commentAdd,proto3" json:"comment_add,omitempty"`
	// Replace text: `id` = existing comment (8 bytes), `text` = new body.
	CommentUpdate []*Comment `protobuf:"bytes,11,rep,name=comment_update,json=commentUpdate,proto3" json:"comment_update,omitempty"`
	// Each entry is the raw 8-byte comment id.
	CommentRemove  [][]byte    `protobuf:"bytes,12,rep,name=comment_remove,json=commentRemove,proto3" json:"comment_remove,omitempty"`
	TagsSet        []string    `protobuf:"bytes,13,rep,name=tags_set,json=tagsSet,proto3" json:"tags_set,omitempty"`
	TagsUnset      []string    `protobuf:"bytes,14,rep,name=tags_unset,json=tagsUnset,proto3" json:"tags_unset,omitempty"`
	CtagsSet       []string    `protobuf:"bytes,15,rep,name=ctags_set,json=ctagsSet,proto3" json:"ctags_set,omitempty"`
	CtagsUnset     []string    `protobuf:"bytes,16,rep,name=ctags_unset,json=ctagsUnset,proto3" json:"ctags_unset,omitempty"`
	MetadataSet    []*Metadata `protobuf:"bytes,17,rep,name=metadata_set,json=metadataSet,proto3" json:"metadata_set,omitempty"`
	MetadataUnset  []string    `protobuf:"bytes,18,rep,name=metadata_unset,json=metadataUnset,proto3" json:"metadata_unset,omitempty"`
	MetadataForget []string    `protobuf:"bytes,19,rep,name=metadata_forget,json=metadataForget,proto3" json:"metadata_forget,omitempty"`
	// When true, indexing this output into the request DB preserves the previous `updatedAt` on that key (digestion / retention).
	SkipRequestUpdatedAt bool `protobuf:"varint,24,opt,name=skip_request_updated_at,json=skipRequestUpdatedAt,proto3" json:"skip_request_updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_threat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{20}
}

func (x *Input) GetIndex() isInput_Index {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *Input) GetDomain() string {
	if x != nil {
		if x, ok := x.Index.(*Input_Domain); ok {
			return x.Domain
		}
	}
	return ""
}

func (x *Input) GetIp() string {
	if x != nil {
		if x, ok := x.Index.(*Input_Ip); ok {
			return x.Ip
		}
	}
	return ""
}

func (x *Input) GetCommentAdd() []*Comment {
	if x != nil {
		return x.CommentAdd
	}
	return nil
}

func (x *Input) GetCommentUpdate() []*Comment {
	if x != nil {
		return x.CommentUpdate
	}
	return nil
}

func (x *Input) GetCommentRemove() [][]byte {
	if x != nil {
		return x.CommentRemove
	}
	return nil
}

func (x *Input) GetTagsSet() []string {
	if x != nil {
		return x.TagsSet
	}
	return nil
}

func (x *Input) GetTagsUnset() []string {
	if x != nil {
		return x.TagsUnset
	}
	return nil
}

func (x *Input) GetCtagsSet() []string {
	if x != nil {
		return x.CtagsSet
	}
	return nil
}

func (x *Input) GetCtagsUnset() []string {
	if x != nil {
		return x.CtagsUnset
	}
	return nil
}

func (x *Input) GetMetadataSet() []*Metadata {
	if x != nil {
		return x.MetadataSet
	}
	return nil
}

func (x *Input) GetMetadataUnset() []string {
	if x != nil {
		return x.MetadataUnset
	}
	return nil
}

func (x *Input) GetMetadataForget() []string {
	if x != nil {
		return x.MetadataForget
	}
	return nil
}

func (x *Input) GetSkipRequestUpdatedAt() bool {
	if x != nil {
		return x.SkipRequestUpdatedAt
	}
	return false
}

type isInput_Index interface {
	isInput_Index()
}

type Input_Domain struct {
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3,oneof"`
}

type Input_Ip struct {
	Ip string `protobuf:"bytes,2,opt,name=ip,proto3,oneof"`
}

func (*Input_Domain) isInput_Index() {}

func (*Input_Ip) isInput_Index() {}

type Output struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index          []byte                 `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	CommentAdd     []*Comment             `protobuf:"bytes,10,rep,name=comment_add,json=commentAdd,proto3" json:"comment_add,omitempty"`
	CommentUpdate  []*Comment             `protobuf:"bytes,11,rep,name=comment_update,json=commentUpdate,proto3" json:"comment_update,omitempty"`
	CommentRemove  [][]byte               `protobuf:"bytes,12,rep,name=comment_remove,json=commentRemove,proto3" json:"comment_remove,omitempty"`
	TagsAdd        []string               `protobuf:"bytes,13,rep,name=tags_add,json=tagsAdd,proto3" json:"tags_add,omitempty"`
	TagsRemove     []string               `protobuf:"bytes,14,rep,name=tags_remove,json=tagsRemove,proto3" json:"tags_remove,omitempty"`
	CtagsAdd       []string               `protobuf:"bytes,15,rep,name=ctags_add,json=ctagsAdd,proto3" json:"ctags_add,omitempty"`
	CtagsRemove    []string               `protobuf:"bytes,16,rep,name=ctags_remove,json=ctagsRemove,proto3" json:"ctags_remove,omitempty"`
	MetadataSet    []*Metadata            `protobuf:"bytes,17,rep,name=metadata_set,json=metadataSet,proto3" json:"metadata_set,omitempty"`
	MetadataUnset  []string               `protobuf:"bytes,18,rep,name=metadata_unset,json=metadataUnset,proto3" json:"metadata_unset,omitempty"`
	MetadataForget []string               `protobuf:"bytes,19,rep,name=metadata_forget,json=metadataForget,proto3" json:"metadata_forget,omitempty"`
	// id is the headers of other list
	// during exchange the foreign party can
	// retrieve header of other by using Header.sum
	MergeAdd    []string `protobuf:"bytes,20,rep,name=merge_add,json=mergeAdd,proto3" json:"merge_add,omitempty"`
	MergeRemove []string `protobuf:"bytes,21,rep,name=merge_remove,json=mergeRemove,proto3" json:"merge_remove,omitempty"`
	// pubkey management
	PubkeyAdd    []string `protobuf:"bytes,22,rep,name=pubkey_add,json=pubkeyAdd,proto3" json:"pubkey_add,omitempty"`
	PubkeyRemove []string `protobuf:"bytes,23,rep,name=pubkey_remove,json=pubkeyRemove,proto3" json:"pubkey_remove,omitempty"`
	// When true, `indexOutputs` does not bump `updatedAt` on the stored request row (see Input.skip_request_updated_at).
	SkipRequestUpdatedAt bool `protobuf:"varint,24,opt,name=skip_request_updated_at,json=skipRequestUpdatedAt,proto3" json:"skip_request_updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_threat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{21}
}

func (x *Output) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Output) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *Output) GetCommentAdd() []*Comment {
	if x != nil {
		return x.CommentAdd
	}
	return nil
}

func (x *Output) GetCommentUpdate() []*Comment {
	if x != nil {
		return x.CommentUpdate
	}
	return nil
}

func (x *Output) GetCommentRemove() [][]byte {
	if x != nil {
		return x.CommentRemove
	}
	return nil
}

func (x *Output) GetTagsAdd() []string {
	if x != nil {
		return x.TagsAdd
	}
	return nil
}

func (x *Output) GetTagsRemove() []string {
	if x != nil {
		return x.TagsRemove
	}
	return nil
}

func (x *Output) GetCtagsAdd() []string {
	if x != nil {
		return x.CtagsAdd
	}
	return nil
}

func (x *Output) GetCtagsRemove() []string {
	if x != nil {
		return x.CtagsRemove
	}
	return nil
}

func (x *Output) GetMetadataSet() []*Metadata {
	if x != nil {
		return x.MetadataSet
	}
	return nil
}

func (x *Output) GetMetadataUnset() []string {
	if x != nil {
		return x.MetadataUnset
	}
	return nil
}

func (x *Output) GetMetadataForget() []string {
	if x != nil {
		return x.MetadataForget
	}
	return nil
}

func (x *Output) GetMergeAdd() []string {
	if x != nil {
		return x.MergeAdd
	}
	return nil
}

func (x *Output) GetMergeRemove() []string {
	if x != nil {
		return x.MergeRemove
	}
	return nil
}

func (x *Output) GetPubkeyAdd() []string {
	if x != nil {
		return x.PubkeyAdd
	}
	return nil
}

func (x *Output) GetPubkeyRemove() []string {
	if x != nil {
		return x.PubkeyRemove
	}
	return nil
}

func (x *Output) GetSkipRequestUpdatedAt() bool {
	if x != nil {
		return x.SkipRequestUpdatedAt
	}
	return false
}

type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Prev  []byte                 `protobuf:"bytes,1,opt,name=prev,proto3" json:"prev,omitempty"`
	// witness timer
	Timestamp int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Outputs   [][]byte `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Sum       []byte   `protobuf:"bytes,4,opt,name=sum,proto3" json:"sum,omitempty"`
	Sign      []byte   `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	// hash of sum + sign
	// attachment point for next block
	Attach        []byte `protobuf:"bytes,6,opt,name=attach,proto3" json:"attach,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_threat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{22}
}

func (x *Block) GetPrev() []byte {
	if x != nil {
		return x.Prev
	}
	return nil
}

func (x *Block) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Block) GetOutputs() [][]byte {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Block) GetSum() []byte {
	if x != nil {
		return x.Sum
	}
	return nil
}

func (x *Block) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *Block) GetAttach() []byte {
	if x != nil {
		return x.Attach
	}
	return nil
}

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Genesis magic number
	Magic         []byte   `protobuf:"bytes,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Nonce         []byte   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Pubkeys       [][]byte `protobuf:"bytes,3,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_threat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{23}
}

func (x *Header) GetMagic() []byte {
	if x != nil {
		return x.Magic
	}
	return nil
}

func (x *Header) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Header) GetPubkeys() [][]byte {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

// Portable bootstrap pack for a chain: paste-friendly protobuf bytes (e.g. base64) so a peer
// can learn bootstrap HTTP(S) / WS URLs and verify genesis. Chain registry id is
// hex(SHA256(Header.encode(genesis_header))) — same as `kernel.crypto.hashHeaderSum(header)`.
// The first on-chain block must use prev = that digest; signatures must verify against
// genesis_header.pubkeys (see `Block` / header docs in BLOCKCHAIN.md).
type BlockchainBootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// When set, must equal hashHeaderSum(genesis_header) as 64 lowercase hex chars (no 0x).
	ExpectedChainId *string `protobuf:"bytes,2,opt,name=expected_chain_id,json=expectedChainId,proto3,oneof" json:"expected_chain_id,omitempty"`
	ChainNameHint   *string `protobuf:"bytes,3,opt,name=chain_name_hint,json=chainNameHint,proto3,oneof" json:"chain_name_hint,omitempty"`
	// Bootstrap / mirror URLs (https://…, wss://…, etc.); order is not significant.
	BootstrapUrls []string `protobuf:"bytes,4,rep,name=bootstrap_urls,json=bootstrapUrls,proto3" json:"bootstrap_urls,omitempty"`
	GenesisHeader *Header  `protobuf:"bytes,5,opt,name=genesis_header,json=genesisHeader,proto3" json:"genesis_header,omitempty"`
	// First block after the header anchor: prev = SHA256(genesis_header wire bytes).
	GenesisBlock *Block `protobuf:"bytes,6,opt,name=genesis_block,json=genesisBlock,proto3" json:"genesis_block,omitempty"`
	// API access token when bootstrap URLs require auth (private handoff). Must be omitted for public distribution.
	ApiAccessToken *string `protobuf:"bytes,7,opt,name=api_access_token,json=apiAccessToken,proto3,oneof" json:"api_access_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockchainBootstrap) Reset() {
	*x = BlockchainBootstrap{}
	mi := &file_threat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockchainBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainBootstrap) ProtoMessage() {}

func (x *BlockchainBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainBootstrap.ProtoReflect.Descriptor instead.
func (*BlockchainBootstrap) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{24}
}

func (x *BlockchainBootstrap) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *BlockchainBootstrap) GetExpectedChainId() string {
	if x != nil && x.ExpectedChainId != nil {
		return *x.ExpectedChainId
	}
	return ""
}

func (x *BlockchainBootstrap) GetChainNameHint() string {
	if x != nil && x.ChainNameHint != nil {
		return *x.ChainNameHint
	}
	return ""
}

func (x *BlockchainBootstrap) GetBootstrapUrls() []string {
	if x != nil {
		return x.BootstrapUrls
	}
	return nil
}

func (x *BlockchainBootstrap) GetGenesisHeader() *Header {
	if x != nil {
		return x.GenesisHeader
	}
	return nil
}

func (x *BlockchainBootstrap) GetGenesisBlock() *Block {
	if x != nil {
		return x.GenesisBlock
	}
	return nil
}

func (x *BlockchainBootstrap) GetApiAccessToken() string {
	if x != nil && x.ApiAccessToken != nil {
		return *x.ApiAccessToken
	}
	return ""
}

type PayloadJsonList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadJsonList) Reset() {
	*x = PayloadJsonList{}
	mi := &file_threat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadJsonList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadJsonList) ProtoMessage() {}

func (x *PayloadJsonList) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadJsonList.ProtoReflect.Descriptor instead.
func (*PayloadJsonList) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{25}
}

func (x *PayloadJsonList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type PayloadRawList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadRawList) Reset() {
	*x = PayloadRawList{}
	mi := &file_threat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadRawList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadRawList) ProtoMessage() {}

func (x *PayloadRawList) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadRawList.ProtoReflect.Descriptor instead.
func (*PayloadRawList) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{26}
}

func (x *PayloadRawList) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type PayloadAuth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  PayloadAuthMode        `protobuf:"varint,1,opt,name=mode,proto3,enum=PayloadAuthMode" json:"mode,omitempty"`
	// mode USER
	Email []string `protobuf:"bytes,2,rep,name=email,proto3" json:"email,omitempty"`
	// mode API
	Password      []string `protobuf:"bytes,3,rep,name=password,proto3" json:"password,omitempty"`
	Secret        []string `protobuf:"bytes,4,rep,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayloadAuth) Reset() {
	*x = PayloadAuth{}
	mi := &file_threat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAuth) ProtoMessage() {}

func (x *PayloadAuth) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAuth.ProtoReflect.Descriptor instead.
func (*PayloadAuth) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{27}
}

func (x *PayloadAuth) GetMode() PayloadAuthMode {
	if x != nil {
		return x.Mode
	}
	return PayloadAuthMode_PAYLOAD_AUTH_MODE_UNSPECIFIED
}

func (x *PayloadAuth) GetEmail() []string {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *PayloadAuth) GetPassword() []string {
	if x != nil {
		return x.Password
	}
	return nil
}

func (x *PayloadAuth) GetSecret() []string {
	if x != nil {
		return x.Secret
	}
	return nil
}

type Payload struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Command string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Types that are valid to be assigned to Types:
	//
	//	*Payload_Json
	//	*Payload_Jsons
	//	*Payload_Raw
	//	*Payload_Raws
	Types         isPayload_Types `protobuf_oneof:"types"`
	Track         []byte          `protobuf:"bytes,6,opt,name=track,proto3" json:"track,omitempty"`
	Auth          *PayloadAuth    `protobuf:"bytes,7,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_threat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{28}
}

func (x *Payload) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Payload) GetTypes() isPayload_Types {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Payload) GetJson() string {
	if x != nil {
		if x, ok := x.Types.(*Payload_Json); ok {
			return x.Json
		}
	}
	return ""
}

func (x *Payload) GetJsons() *PayloadJsonList {
	if x != nil {
		if x, ok := x.Types.(*Payload_Jsons); ok {
			return x.Jsons
		}
	}
	return nil
}

func (x *Payload) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Types.(*Payload_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *Payload) GetRaws() *PayloadRawList {
	if x != nil {
		if x, ok := x.Types.(*Payload_Raws); ok {
			return x.Raws
		}
	}
	return nil
}

func (x *Payload) GetTrack() []byte {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *Payload) GetAuth() *PayloadAuth {
	if x != nil {
		return x.Auth
	}
	return nil
}

type isPayload_Types interface {
	isPayload_Types()
}

type Payload_Json struct {
	Json string `protobuf:"bytes,2,opt,name=json,proto3,oneof"`
}

type Payload_Jsons struct {
	Jsons *PayloadJsonList `protobuf:"bytes,3,opt,name=jsons,proto3,oneof"`
}

type Payload_Raw struct {
	Raw []byte `protobuf:"bytes,4,opt,name=raw,proto3,oneof"`
}

type Payload_Raws struct {
	Raws *PayloadRawList `protobuf:"bytes,5,opt,name=raws,proto3,oneof"`
}

func (*Payload_Json) isPayload_Types() {}

func (*Payload_Jsons) isPayload_Types() {}

func (*Payload_Raw) isPayload_Types() {}

func (*Payload_Raws) isPayload_Types() {}

// Full-chain LevelDB output queue (`queue:meta:*`, `queue:staging`): wire is protobuf end-to-end.
type QueueMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextSeq       uint64                 `protobuf:"varint,1,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMeta) Reset() {
	*x = QueueMeta{}
	mi := &file_threat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMeta) ProtoMessage() {}

func (x *QueueMeta) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMeta.ProtoReflect.Descriptor instead.
func (*QueueMeta) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{29}
}

func (x *QueueMeta) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

type QueueStagingEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqPadded     string                 `protobuf:"bytes,1,opt,name=seq_padded,json=seqPadded,proto3" json:"seq_padded,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStagingEntry) Reset() {
	*x = QueueStagingEntry{}
	mi := &file_threat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStagingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStagingEntry) ProtoMessage() {}

func (x *QueueStagingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStagingEntry.ProtoReflect.Descriptor instead.
func (*QueueStagingEntry) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{30}
}

func (x *QueueStagingEntry) GetSeqPadded() string {
	if x != nil {
		return x.SeqPadded
	}
	return ""
}

func (x *QueueStagingEntry) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type QueueStaging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FormatVersion uint32                 `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	TargetPrevHex string                 `protobuf:"bytes,2,opt,name=target_prev_hex,json=targetPrevHex,proto3" json:"target_prev_hex,omitempty"`
	Entries       []*QueueStagingEntry   `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStaging) Reset() {
	*x = QueueStaging{}
	mi := &file_threat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStaging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStaging) ProtoMessage() {}

func (x *QueueStaging) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStaging.ProtoReflect.Descriptor instead.
func (*QueueStaging) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{31}
}

func (x *QueueStaging) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *QueueStaging) GetTargetPrevHex() string {
	if x != nil {
		return x.TargetPrevHex
	}
	return ""
}

func (x *QueueStaging) GetEntries() []*QueueStagingEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RequestEntryTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RequestFieldToken   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEntryTokens) Reset() {
	*x = RequestEntryTokens{}
	mi := &file_threat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEntryTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEntryTokens) ProtoMessage() {}

func (x *RequestEntryTokens) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEntryTokens.ProtoReflect.Descriptor instead.
func (*RequestEntryTokens) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{32}
}

func (x *RequestEntryTokens) GetItems() []*RequestFieldToken {
	if x != nil {
		return x.Items
	}
	return nil
}

type RequestFieldToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         RequestField           `protobuf:"varint,1,opt,name=field,proto3,enum=RequestField" json:"field,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFieldToken) Reset() {
	*x = RequestFieldToken{}
	mi := &file_threat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFieldToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFieldToken) ProtoMessage() {}

func (x *RequestFieldToken) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFieldToken.ProtoReflect.Descriptor instead.
func (*RequestFieldToken) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{33}
}

func (x *RequestFieldToken) GetField() RequestField {
	if x != nil {
		return x.Field
	}
	return RequestField_RF_DOMAIN
}

func (x *RequestFieldToken) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RequestQueueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         []byte                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Storage       []byte                 `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	IsDelete      bool                   `protobuf:"varint,3,opt,name=is_delete,json=isDelete,proto3" json:"is_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestQueueItem) Reset() {
	*x = RequestQueueItem{}
	mi := &file_threat_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestQueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueueItem) ProtoMessage() {}

func (x *RequestQueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestQueueItem.ProtoReflect.Descriptor instead.
func (*RequestQueueItem) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{34}
}

func (x *RequestQueueItem) GetIndex() []byte {
	if x != nil {
		return x.Index
	}
	return nil
}

func (x *RequestQueueItem) GetStorage() []byte {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *RequestQueueItem) GetIsDelete() bool {
	if x != nil {
		return x.IsDelete
	}
	return false
}

type RequestMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextSeq       uint64                 `protobuf:"varint,1,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	EntryCount    uint64                 `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	mi := &file_threat_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_threat_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_threat_proto_rawDescGZIP(), []int{35}
}

func (x *RequestMeta) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *RequestMeta) GetEntryCount() uint64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

var File_threat_proto protoreflect.FileDescriptor

const file_threat_proto_rawDesc = "" +
	"\n" +
	"\fthreat.proto\"4\n" +
	"\n" +
	"PrivateKey\x12\x12\n" +
	"\x04algo\x18\x01 \x01(\tR\x04algo\x12\x12\n" +
	"\x04priv\x18\x02 \x01(\fR\x04priv\"1\n" +
	"\tPublicKey\x12\x12\n" +
	"\x04algo\x18\x01 \x01(\tR\x04algo\x12\x10\n" +
	"\x03pub\x18\x02 \x01(\fR\x03pub\"8\n" +
	"\x06Domain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bwildcard\x18\x02 \x01(\bR\bwildcard\"@\n" +
	"\x10InternetProtocol\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x12\n" +
	"\x04mask\x18\x02 \x01(\x05R\x04mask\"\x99\x02\n" +
	"\aStorage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x19\n" +
	"\x04type\x18\x02 \x01(\x0e2\x05.TypeR\x04type\x12!\n" +
	"\x06domain\x18\x03 \x01(\v2\a.DomainH\x00R\x06domain\x12#\n" +
	"\x02ip\x18\x04 \x01(\v2\x11.InternetProtocolH\x00R\x02ip\x12\x14\n" +
	"\x05first\x18\x05 \x01(\x03R\x05first\x12\x12\n" +
	"\x04last\x18\x06 \x01(\x03R\x04last\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1a\n" +
	"\bcomments\x18\b \x03(\tR\bcomments\x12\x14\n" +
	"\x05ctags\x18\t \x03(\tR\x05ctags\x12\x1c\n" +
	"\tmetadatas\x18\n" +
	" \x03(\tR\tmetadatasB\r\n" +
	"\vinformation\"D\n" +
	"\x0eCommitInputRow\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x1c\n" +
	"\x05input\x18\x02 \x01(\v2\x06.InputR\x05input\"\xa3\x01\n" +
	"\x10CommitItemsQuery\x12\x15\n" +
	"\x03idx\x18\x01 \x01(\rH\x00R\x03idx\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x1b\n" +
	"\x06anchor\x18\x05 \x01(\tH\x02R\x06anchor\x88\x01\x01B\x06\n" +
	"\x04_idxB\x05\n" +
	"\x03_idB\t\n" +
	"\a_anchor\"\xb3\x01\n" +
	"\x11CommitItemsResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03idx\x18\x02 \x01(\rR\x03idx\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\x12%\n" +
	"\x05items\x18\x04 \x03(\v2\x0f.CommitInputRowR\x05items\x12$\n" +
	"\vprev_cursor\x18\x05 \x01(\tH\x00R\n" +
	"prevCursor\x88\x01\x01B\x0e\n" +
	"\f_prev_cursor\"T\n" +
	"\x15CommitStoragePutEntry\x12\x1d\n" +
	"\n" +
	"index_utf8\x18\x01 \x01(\tR\tindexUtf8\x12\x1c\n" +
	"\x05input\x18\x02 \x01(\v2\x06.InputR\x05input\"\xbf\x01\n" +
	"\x17CommitStoragePutRequest\x12\x15\n" +
	"\x03idx\x18\x01 \x01(\rH\x00R\x03idx\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01\x120\n" +
	"\aentries\x18\x03 \x03(\v2\x16.CommitStoragePutEntryR\aentries\x12&\n" +
	"\fimport_merge\x18\x04 \x01(\bH\x02R\vimportMerge\x88\x01\x01B\x06\n" +
	"\x04_idxB\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_import_merge\"s\n" +
	"\x16CommitStoragePutResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03idx\x18\x02 \x01(\rR\x03idx\x12\x18\n" +
	"\aindices\x18\x03 \x03(\tR\aindices\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"\x83\x01\n" +
	"\x17CommitStorageSizeResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x10\n" +
	"\x03idx\x18\x02 \x01(\rR\x03idx\x12!\n" +
	"\fcommit_bytes\x18\x03 \x01(\x04R\vcommitBytes\x12#\n" +
	"\rrequest_bytes\x18\x04 \x01(\x04R\frequestBytes\"\xc0\x01\n" +
	"\x1bBlockchainStorageSizeResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vchain_bytes\x18\x03 \x01(\x04R\n" +
	"chainBytes\x12#\n" +
	"\rrequest_bytes\x18\x04 \x01(\x04R\frequestBytes\x12;\n" +
	"\x1akernel_request_index_bytes\x18\x05 \x01(\x04R\x17kernelRequestIndexBytes\"2\n" +
	" BlockchainExplorerControlRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"u\n" +
	"\x1fBlockchainExplorerControlResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\astarted\x18\x03 \x01(\bR\astarted\x12\x18\n" +
	"\astopped\x18\x04 \x01(\bR\astopped\"z\n" +
	"\x1dBlockchainExplorerListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tblock_sum\x18\x02 \x01(\tR\bblockSum\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\x83\x01\n" +
	"\x17BlockchainExplorerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1b\n" +
	"\tblock_sum\x18\x02 \x01(\tR\bblockSum\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\rR\aordinal\x12\x1f\n" +
	"\x06output\x18\x04 \x01(\v2\a.OutputR\x06output\"\x93\x01\n" +
	"\x1cBlockchainExplorerListResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x122\n" +
	"\aentries\x18\x03 \x03(\v2\x18.BlockchainExplorerEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\"2\n" +
	"\bMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"-\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xec\x03\n" +
	"\x05Input\x12\x18\n" +
	"\x06domain\x18\x01 \x01(\tH\x00R\x06domain\x12\x10\n" +
	"\x02ip\x18\x02 \x01(\tH\x00R\x02ip\x12)\n" +
	"\vcomment_add\x18\n" +
	" \x03(\v2\b.CommentR\n" +
	"commentAdd\x12/\n" +
	"\x0ecomment_update\x18\v \x03(\v2\b.CommentR\rcommentUpdate\x12%\n" +
	"\x0ecomment_remove\x18\f \x03(\fR\rcommentRemove\x12\x19\n" +
	"\btags_set\x18\r \x03(\tR\atagsSet\x12\x1d\n" +
	"\n" +
	"tags_unset\x18\x0e \x03(\tR\ttagsUnset\x12\x1b\n" +
	"\tctags_set\x18\x0f \x03(\tR\bctagsSet\x12\x1f\n" +
	"\vctags_unset\x18\x10 \x03(\tR\n" +
	"ctagsUnset\x12,\n" +
	"\fmetadata_set\x18\x11 \x03(\v2\t.MetadataR\vmetadataSet\x12%\n" +
	"\x0emetadata_unset\x18\x12 \x03(\tR\rmetadataUnset\x12'\n" +
	"\x0fmetadata_forget\x18\x13 \x03(\tR\x0emetadataForget\x125\n" +
	"\x17skip_request_updated_at\x18\x18 \x01(\bR\x14skipRequestUpdatedAtB\a\n" +
	"\x05index\"\xe6\x04\n" +
	"\x06Output\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\fR\x05index\x12)\n" +
	"\vcomment_add\x18\n" +
	" \x03(\v2\b.CommentR\n" +
	"commentAdd\x12/\n" +
	"\x0ecomment_update\x18\v \x03(\v2\b.CommentR\rcommentUpdate\x12%\n" +
	"\x0ecomment_remove\x18\f \x03(\fR\rcommentRemove\x12\x19\n" +
	"\btags_add\x18\r \x03(\tR\atagsAdd\x12\x1f\n" +
	"\vtags_remove\x18\x0e \x03(\tR\n" +
	"tagsRemove\x12\x1b\n" +
	"\tctags_add\x18\x0f \x03(\tR\bctagsAdd\x12!\n" +
	"\fctags_remove\x18\x10 \x03(\tR\vctagsRemove\x12,\n" +
	"\fmetadata_set\x18\x11 \x03(\v2\t.MetadataR\vmetadataSet\x12%\n" +
	"\x0emetadata_unset\x18\x12 \x03(\tR\rmetadataUnset\x12'\n" +
	"\x0fmetadata_forget\x18\x13 \x03(\tR\x0emetadataForget\x12\x1b\n" +
	"\tmerge_add\x18\x14 \x03(\tR\bmergeAdd\x12!\n" +
	"\fmerge_remove\x18\x15 \x03(\tR\vmergeRemove\x12\x1d\n" +
	"\n" +
	"pubkey_add\x18\x16 \x03(\tR\tpubkeyAdd\x12#\n" +
	"\rpubkey_remove\x18\x17 \x03(\tR\fpubkeyRemove\x125\n" +
	"\x17skip_request_updated_at\x18\x18 \x01(\bR\x14skipRequestUpdatedAt\"\x91\x01\n" +
	"\x05Block\x12\x12\n" +
	"\x04prev\x18\x01 \x01(\fR\x04prev\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aoutputs\x18\x03 \x03(\fR\aoutputs\x12\x10\n" +
	"\x03sum\x18\x04 \x01(\fR\x03sum\x12\x12\n" +
	"\x04sign\x18\x05 \x01(\fR\x04sign\x12\x16\n" +
	"\x06attach\x18\x06 \x01(\fR\x06attach\"N\n" +
	"\x06Header\x12\x14\n" +
	"\x05magic\x18\x01 \x01(\fR\x05magic\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x18\n" +
	"\apubkeys\x18\x03 \x03(\fR\apubkeys\"\x8c\x03\n" +
	"\x13BlockchainBootstrap\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12/\n" +
	"\x11expected_chain_id\x18\x02 \x01(\tH\x00R\x0fexpectedChainId\x88\x01\x01\x12+\n" +
	"\x0fchain_name_hint\x18\x03 \x01(\tH\x01R\rchainNameHint\x88\x01\x01\x12%\n" +
	"\x0ebootstrap_urls\x18\x04 \x03(\tR\rbootstrapUrls\x12.\n" +
	"\x0egenesis_header\x18\x05 \x01(\v2\a.HeaderR\rgenesisHeader\x12+\n" +
	"\rgenesis_block\x18\x06 \x01(\v2\x06.BlockR\fgenesisBlock\x12-\n" +
	"\x10api_access_token\x18\a \x01(\tH\x02R\x0eapiAccessToken\x88\x01\x01B\x14\n" +
	"\x12_expected_chain_idB\x12\n" +
	"\x10_chain_name_hintB\x13\n" +
	"\x11_api_access_token\")\n" +
	"\x0fPayloadJsonList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"(\n" +
	"\x0ePayloadRawList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"}\n" +
	"\vPayloadAuth\x12$\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x10.PayloadAuthModeR\x04mode\x12\x14\n" +
	"\x05email\x18\x02 \x03(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x03(\tR\bpassword\x12\x16\n" +
	"\x06secret\x18\x04 \x03(\tR\x06secret\"\xdf\x01\n" +
	"\aPayload\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x14\n" +
	"\x04json\x18\x02 \x01(\tH\x00R\x04json\x12(\n" +
	"\x05jsons\x18\x03 \x01(\v2\x10.PayloadJsonListH\x00R\x05jsons\x12\x12\n" +
	"\x03raw\x18\x04 \x01(\fH\x00R\x03raw\x12%\n" +
	"\x04raws\x18\x05 \x01(\v2\x0f.PayloadRawListH\x00R\x04raws\x12\x14\n" +
	"\x05track\x18\x06 \x01(\fR\x05track\x12 \n" +
	"\x04auth\x18\a \x01(\v2\f.PayloadAuthR\x04authB\a\n" +
	"\x05types\"&\n" +
	"\tQueueMeta\x12\x19\n" +
	"\bnext_seq\x18\x01 \x01(\x04R\anextSeq\"J\n" +
	"\x11QueueStagingEntry\x12\x1d\n" +
	"\n" +
	"seq_padded\x18\x01 \x01(\tR\tseqPadded\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\"\x8b\x01\n" +
	"\fQueueStaging\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x12&\n" +
	"\x0ftarget_prev_hex\x18\x02 \x01(\tR\rtargetPrevHex\x12,\n" +
	"\aentries\x18\x03 \x03(\v2\x12.QueueStagingEntryR\aentries\">\n" +
	"\x12RequestEntryTokens\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.RequestFieldTokenR\x05items\"N\n" +
	"\x11RequestFieldToken\x12#\n" +
	"\x05field\x18\x01 \x01(\x0e2\r.RequestFieldR\x05field\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"_\n" +
	"\x10RequestQueueItem\x12\x14\n" +
	"\x05index\x18\x01 \x01(\fR\x05index\x12\x18\n" +
	"\astorage\x18\x02 \x01(\fR\astorage\x12\x1b\n" +
	"\tis_delete\x18\x03 \x01(\bR\bisDelete\"I\n" +
	"\vRequestMeta\x12\x19\n" +
	"\bnext_seq\x18\x01 \x01(\x04R\anextSeq\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\x04R\n" +
	"entryCount*<\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06DOMAIN\x10\x01\x12\b\n" +
	"\x04IPv4\x10\x02\x12\b\n" +
	"\x04IPv6\x10\x03*G\n" +
	"\x0fPayloadAuthMode\x12!\n" +
	"\x1dPAYLOAD_AUTH_MODE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\a\n" +
	"\x03API\x10\x02*u\n" +
	"\fRequestField\x12\r\n" +
	"\tRF_DOMAIN\x10\x00\x12\t\n" +
	"\x05RF_IP\x10\x01\x12\n" +
	"\n" +
	"\x06RF_TAG\x10\x02\x12\x0e\n" +
	"\n" +
	"RF_COMMENT\x10\x03\x12\v\n" +
	"\aRF_CTAG\x10\x04\x12\x0f\n" +
	"\vRF_META_KEY\x10\x05\x12\x11\n" +
	"\rRF_META_VALUE\x10\x06B'Z%github.com/protothreat/go/pb;threatpbb\x06proto3"

var (
	file_threat_proto_rawDescOnce sync.Once
	file_threat_proto_rawDescData []byte
)

func file_threat_proto_rawDescGZIP() []byte {
	file_threat_proto_rawDescOnce.Do(func() {
		file_threat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_threat_proto_rawDesc), len(file_threat_proto_rawDesc)))
	})
	return file_threat_proto_rawDescData
}

var file_threat_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_threat_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_threat_proto_goTypes = []any{
	(Type)(0),                                // 0: Type
	(PayloadAuthMode)(0),                     // 1: PayloadAuthMode
	(RequestField)(0),                        // 2: RequestField
	(*PrivateKey)(nil),                       // 3: PrivateKey
	(*PublicKey)(nil),                        // 4: PublicKey
	(*Domain)(nil),                           // 5: Domain
	(*InternetProtocol)(nil),                 // 6: InternetProtocol
	(*Storage)(nil),                          // 7: Storage
	(*CommitInputRow)(nil),                   // 8: CommitInputRow
	(*CommitItemsQuery)(nil),                 // 9: CommitItemsQuery
	(*CommitItemsResult)(nil),                // 10: CommitItemsResult
	(*CommitStoragePutEntry)(nil),            // 11: CommitStoragePutEntry
	(*CommitStoragePutRequest)(nil),          // 12: CommitStoragePutRequest
	(*CommitStoragePutResult)(nil),           // 13: CommitStoragePutResult
	(*CommitStorageSizeResult)(nil),          // 14: CommitStorageSizeResult
	(*BlockchainStorageSizeResult)(nil),      // 15: BlockchainStorageSizeResult
	(*BlockchainExplorerControlRequest)(nil), // 16: BlockchainExplorerControlRequest
	(*BlockchainExplorerControlResult)(nil),  // 17: BlockchainExplorerControlResult
	(*BlockchainExplorerListRequest)(nil),    // 18: BlockchainExplorerListRequest
	(*BlockchainExplorerEntry)(nil),          // 19: BlockchainExplorerEntry
	(*BlockchainExplorerListResult)(nil),     // 20: BlockchainExplorerListResult
	(*Metadata)(nil),                         // 21: Metadata
	(*Comment)(nil),                          // 22: Comment
	(*Input)(nil),                            // 23: Input
	(*Output)(nil),                           // 24: Output
	(*Block)(nil),                            // 25: Block
	(*Header)(nil),                           // 26: Header
	(*BlockchainBootstrap)(nil),              // 27: BlockchainBootstrap
	(*PayloadJsonList)(nil),                  // 28: PayloadJsonList
	(*PayloadRawList)(nil),                   // 29: PayloadRawList
	(*PayloadAuth)(nil),                      // 30: PayloadAuth
	(*Payload)(nil),                          // 31: Payload
	(*QueueMeta)(nil),                        // 32: QueueMeta
	(*QueueStagingEntry)(nil),                // 33: QueueStagingEntry
	(*QueueStaging)(nil),                     // 34: QueueStaging
	(*RequestEntryTokens)(nil),               // 35: RequestEntryTokens
	(*RequestFieldToken)(nil),                // 36: RequestFieldToken
	(*RequestQueueItem)(nil),                 // 37: RequestQueueItem
	(*RequestMeta)(nil),                      // 38: RequestMeta
}
var file_threat_proto_depIdxs = []int32{
	0,  // 0: Storage.type:type_name -> Type
	5,  // 1: Storage.domain:type_name -> Domain
	6,  // 2: Storage.ip:type_name -> InternetProtocol
	23, // 3: CommitInputRow.input:type_name -> Input
	8,  // 4: CommitItemsResult.items:type_name -> CommitInputRow
	23, // 5: CommitStoragePutEntry.input:type_name -> Input
	11, // 6: CommitStoragePutRequest.entries:type_name -> CommitStoragePutEntry
	24, // 7: BlockchainExplorerEntry.output:type_name -> Output
	19, // 8: BlockchainExplorerListResult.entries:type_name -> BlockchainExplorerEntry
	22, // 9: Input.comment_add:type_name -> Comment
	22, // 10: Input.comment_update:type_name -> Comment
	21, // 11: Input.metadata_set:type_name -> Metadata
	22, // 12: Output.comment_add:type_name -> Comment
	22, // 13: Output.comment_update:type_name -> Comment
	21, // 14: Output.metadata_set:type_name -> Metadata
	26, // 15: BlockchainBootstrap.genesis_header:type_name -> Header
	25, // 16: BlockchainBootstrap.genesis_block:type_name -> Block
	1,  // 17: PayloadAuth.mode:type_name -> PayloadAuthMode
	28, // 18: Payload.jsons:type_name -> PayloadJsonList
	29, // 19: Payload.raws:type_name -> PayloadRawList
	30, // 20: Payload.auth:type_name -> PayloadAuth
	33, // 21: QueueStaging.entries:type_name -> QueueStagingEntry
	36, // 22: RequestEntryTokens.items:type_name -> RequestFieldToken
	2,  // 23: RequestFieldToken.field:type_name -> RequestField
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_threat_proto_init() }
func file_threat_proto_init() {
	if File_threat_proto != nil {
		return
	}
	file_threat_proto_msgTypes[4].OneofWrappers = []any{
		(*Storage_Domain)(nil),
		(*Storage_Ip)(nil),
	}
	file_threat_proto_msgTypes[6].OneofWrappers = []any{}
	file_threat_proto_msgTypes[7].OneofWrappers = []any{}
	file_threat_proto_msgTypes[9].OneofWrappers = []any{}
	file_threat_proto_msgTypes[20].OneofWrappers = []any{
		(*Input_Domain)(nil),
		(*Input_Ip)(nil),
	}
	file_threat_proto_msgTypes[24].OneofWrappers = []any{}
	file_threat_proto_msgTypes[28].OneofWrappers = []any{
		(*Payload_Json)(nil),
		(*Payload_Jsons)(nil),
		(*Payload_Raw)(nil),
		(*Payload_Raws)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_threat_proto_rawDesc), len(file_threat_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_threat_proto_goTypes,
		DependencyIndexes: file_threat_proto_depIdxs,
		EnumInfos:         file_threat_proto_enumTypes,
		MessageInfos:      file_threat_proto_msgTypes,
	}.Build()
	File_threat_proto = out.File
	file_threat_proto_goTypes = nil
	file_threat_proto_depIdxs = nil
}
